services:
  frontendadmin:
    build:
      dockerfile: Dockerfile
      context: ./front_end_admin
    
    # environment:
    #   REACT_APP_API_ENDPOINT: http://backend:5000

    ports:
      - 3000:3000
  
    # volumes:
    #   - ./frontend:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: always
    networks:
      - network1
    
    depends_on:
      - backend

  frontenuser:
    build:
     
      dockerfile: Dockerfile
      context: ./front_end_user
    
    # environment:
    #   REACT_APP_API_ENDPOINT: http://backend:5000
      
    ports:
      - 4200:4200
  
    # volumes:
    #   - ./frontend:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: always
    networks:
      - network1
    depends_on:
      - backend

  backend:
   
    build:
        dockerfile: Dockerfile
        context: ./backend
 
    ports:
      - 5000:5000
    
    # expose: 
    #   - 5000
    # volumes:
    #   - ./backend:/usr/src/app
    #   - /usr/src/app/node_modules

    restart: always
    networks:
      - network1

networks:
  network1:
    driver: bridge
