export const columns = [
    {
        field: 'id',
        headerName: 'ID',
        width: 90,
        align: 'center',
        headerAlign: 'center',
    },
    {
        field: 'name',
        headerName: 'Name',
        width: 250,
        editable: true,
        align: 'center',
        headerAlign: 'center',
    },
    {
        field: 'numOfProd',
        headerName: 'Number of product',
        flex: 2,
        editable: true,
        align: 'center',
        headerAlign: 'center',
    },
    {
        field: 'priceDiscount',
        headerName: 'Price Discount',
        width: 200,
        editable: true,
        align: 'center',
        headerAlign: 'center',
    },
    {
        field: 'transportMethod',
        headerName: 'Transport Method',
        flex: 3,
        editable: true,
        align: 'center',
        headerAlign: 'center',
    },
    {
        field: 'paymentMethod',
        headerName: 'Payment Method',
        flex: 3,
        editable: true,
        align: 'center',
        headerAlign: 'center',
    },
]