export const columns = [
    {
        field: 'id',
        headerName: 'ID',
        width: 90,
        align: 'center',
        headerAlign: 'center',
    },
    {
        field: 'name',
        headerName: 'Name',
        width: 250,
        editable: true,
        align: 'center',
        headerAlign: 'center',
    },
    {
        field: 'brand',
        headerName: 'Brand',
        flex: 2,
        editable: true,
        align: 'center',
        headerAlign: 'center',
    },
    {
        field: 'countInStock',
        headerName: 'Count In Stock',
        width: 200,
        editable: true,
        align: 'center',
        headerAlign: 'center',
    },
    {
        field: 'price',
        headerName: 'Price',
        flex: 3,
        editable: true,
        align: 'center',
        headerAlign: 'center',
    },
    {
        field: 'priceDiscount',
        headerName: 'Price Discount',
        flex: 3,
        editable: true,
        align: 'center',
        headerAlign: 'center',
    },
]