export const columns = [
    {
      field: 'id',
      headerName: 'ID',
      width: 90,
      align: 'center',
      headerAlign: 'center',
    },
    {
      field: 'name',
      headerName: 'Name',
      width: 250,
      editable: true,
      align: 'center',
      headerAlign: 'center',
    },
    {
      field: 'email',
      headerName: 'Email',
      flex: 2,
      editable: true,
      align: 'center',
      headerAlign: 'center',
    },
    {
      field: 'quyen',
      headerName: 'Quyen',
      width: 200,
      editable: true,
      align: 'center',
      headerAlign: 'center',
    },
    {
      field: 'diaChi',
      headerName: 'Dia chi',
      flex: 3,
      editable: true,
      align: 'center',
      headerAlign: 'center',
    },
  ]