export const CART_ADD_PRODUCT_SUCCESS = 'CART_ADD_PRODUCT_SUCCESS'

export const CART_DELETE_PRODUCT_SUCCESS = 'CART_DELETE_PRODUCT_SUCCESS'

export const CART_DELETE_MANY_PRODUCT_SUCCESS = 'CART_DELETE_MANY_PRODUCT_SUCCESS'

export const CART_UPDATE_PRODUCT_SUCCESS = 'CART_UPDATE_PRODUCT_SUCCESS'

export const CART_RESET_PRODUCT = 'CART_RESET_PRODUCT'






