export const  DELIVERY_ADDRESS_LIST_REQUEST = ' DELIVERY_ADDRESS_LIST_REQUEST'
export const  DELIVERY_ADDRESS_LIST_SUCCESS = ' DELIVERY_ADDRESS_LIST_SUCCESS'
export const  DELIVERY_ADDRESS_LIST_FAIL = ' DELIVERY_ADDRESS_LIST_FAIL'

export const  CURRENT_DELIVERY_ADDRESS = ' CURRENT_DELIVERY_ADDRESS'

export const  DELIVERY_ADDRESS_ADD_REQUEST = ' DELIVERY_ADDRESS_ADD_REQUEST'
export const  DELIVERY_ADDRESS_ADD_SUCCESS = ' DELIVERY_ADDRESS_ADD_SUCCESS'
export const  DELIVERY_ADDRESS_ADD_FAIL = ' DELIVERY_ADDRESS_ADD_FAIL'
export const  DELIVERY_ADDRESS_ADD_RESET = ' DELIVERY_ADDRESS_ADD_RESET'

export const  DELIVERY_ADDRESS_UPDATE_REQUEST = ' DELIVERY_ADDRESS_UPDATE_REQUEST'
export const  DELIVERY_ADDRESS_UPDATE_SUCCESS = ' DELIVERY_ADDRESS_UPDATE_SUCCESS'
export const  DELIVERY_ADDRESS_UPDATE_FAIL = ' DELIVERY_ADDRESS_UPDATE_FAIL'
export const  DELIVERY_ADDRESS_UPDATE_RESET = ' DELIVERY_ADDRESS_UPDATE_RESET'
