export const  CREATE_ORDER_REQUEST = ' CREATE_ORDER_REQUEST'
export const  CREATE_ORDER_SUCCESS = ' CREATE_ORDER_SUCCESS'
export const  CREATE_ORDER_FAIL = ' CREATE_ORDER_FAIL'

export const  ORDER_CREATE_RESET = ' ORDER_CREATE_RESET'

export const LIST_MY_ORDER_REQUEST = 'LIST_MY_ORDER_REQUEST'
export const LIST_MY_ORDER_SUCCESS = 'LIST_MY_ORDER_SUCCESS'
export const LIST_MY_ORDER_FAIL = 'LIST_MY_ORDER_FAIL'