export const  CREATE_ORDER_REQUEST = ' CREATE_ORDER_REQUEST'
export const  CREATE_ORDER_SUCCESS = ' CREATE_ORDER_SUCCESS'
export const  CREATE_ORDER_FAIL = ' CREATE_ORDER_FAIL'

export const  ORDER_CREATE_RESET = ' ORDER_CREATE_RESET'

export const LIST_MY_ORDER_REQUEST = 'LIST_MY_ORDER_REQUEST'
export const LIST_MY_ORDER_SUCCESS = 'LIST_MY_ORDER_SUCCESS'
export const LIST_MY_ORDER_FAIL = 'LIST_MY_ORDER_FAIL'

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
export const ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL'

export const ORDER_DESTROY_REQUEST = 'ORDER_DESTROY_REQUEST'
export const ORDER_DESTROY_SUCCESS = 'ORDER_DESTROY_SUCCESS'
export const ORDER_DESTROY_FAIL = 'ORDER_DESTROY_FAIL'
export const ORDER_DESTROY_RESET = 'ORDER_DESTROY_RESET'


export const ORDER_CONFIRM_RECEIVED_REQUEST = 'ORDER_CONFIRM_RECEIVED_REQUEST'
export const ORDER_CONFIRM_RECEIVED_SUCCESS = 'ORDER_CONFIRM_RECEIVED_SUCCESS'
export const ORDER_CONFIRM_RECEIVED_FAIL = 'ORDER_CONFIRM_RECEIVED_FAIL'
export const ORDER_CONFIRM_RECEIVED_RESET = 'ORDER_CONFIRM_RECEIVED_RESET'