export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT = 'LOGOUT'

export const LIST_USER_REQUEST = 'LIST_USER_REQUEST'
export const LIST_USER_SUCCESS = 'LIST_USER_SUCCESS'
export const LIST_USER_FAIL = 'LIST_USER_FAIL'

export const DETAIL_USER_REQUEST = 'DETAIL_USER_REQUEST'
export const DETAIL_USER_SUCCESS = 'DETAIL_USER_SUCCESS'
export const DETAIL_USER_FAIL = 'DETAIL_USER_FAIL'

export const ACCEPT_ADMIN_REQUEST = 'ACCEPT_ADMIN_REQUEST'
export const ACCEPT_ADMIN_SUCCESS = 'ACCEPT_ADMIN_SUCCESS'
export const ACCEPT_ADMIN_FAIL = 'ACCEPT_ADMIN_FAIL'

export const PROFILE_REQUEST = 'PROFILE_REQUEST'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_FAIL = 'PROFILE_FAIL'

